[package]
name = "rscrc32"
version = "0.2.0"
authors = ["andrew"]
edition = "2018"

[dependencies]
crc32fast = "1.3.2"
memmap2 = "0.5.8"
oneshot = "0.1.5"
rayon = "1.5.3"

[[bin]]
name = "crc32"
path = "src/main.rs"

[profile.release]
panic = "abort"
